// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'itemWithdraw.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ItemWithdraw _$ItemWithdrawFromJson(Map<String, dynamic> json) => ItemWithdraw(
      sup_item_id: (json['sup_item_id'] as num?)?.toInt(),
      stock_department: (json['stock_department'] as num?)?.toInt(),
      dept_current_balance: json['dept_current_balance'] as String?,
      stock_current_balance: json['stock_current_balance'] as String?,
      sup_item: json['sup_item'] == null
          ? null
          : SupItem.fromJson(json['sup_item'] as Map<String, dynamic>),
      id: (json['id'] as num?)?.toInt(),
      doc_type: json['doc_type'] as String?,
      type: json['type'] as String?,
      sup_control_register_id: json['sup_control_register_id'] as String?,
      sup_acceptance_id: json['sup_acceptance_id'] as String?,
      sup_withdraw_id: json['sup_withdraw_id'] as String?,
      sup_transfer_id: json['sup_transfer_id'] as String?,
      sup_return_id: json['sup_return_id'] as String?,
      sup_borrow_id: json['sup_borrow_id'] as String?,
      date: json['date'] as String?,
      stock: (json['stock'] as num?)?.toInt(),
      qty: (json['qty'] as num?)?.toInt(),
      balance: (json['balance'] as num?)?.toInt(),
      price_per_unit: json['price_per_unit'] as String?,
      price: json['price'] as String?,
      price_pay: json['price_pay'] as String?,
      discount: json['discount'] as String?,
      total: json['total'] as String?,
      hr_ci_department_id: (json['hr_ci_department_id'] as num?)?.toInt(),
      hr_ci_department_2_id: (json['hr_ci_department_2_id'] as num?)?.toInt(),
      status: json['status'] as bool?,
      sup_vendor_id: json['sup_vendor_id'] as String?,
      exp_date: json['exp_date'] as String?,
      sup_item_return_id: json['sup_item_return_id'] as String?,
      lot_maker: json['lot_maker'] as String?,
      asset_status: json['asset_status'] as String?,
      price_stock: json['price_stock'] as String?,
      price_qty: json['price_qty'] as String?,
      price_balance: json['price_balance'] as String?,
      sup_sub_withdraw_id: (json['sup_sub_withdraw_id'] as num?)?.toInt(),
      qty_req_withdraw: (json['qty_req_withdraw'] as num?)?.toInt(),
      sup_deposit_id: json['sup_deposit_id'] as String?,
      brand: json['brand'] as String?,
      model: json['model'] as String?,
      sup_acceptance_free_id: json['sup_acceptance_free_id'] as String?,
      sup_unit_id: (json['sup_unit_id'] as num?)?.toInt(),
      volume: (json['volume'] as num?)?.toInt(),
      pack: (json['pack'] as num?)?.toInt(),
      register_asset_status: json['register_asset_status'] as bool?,
      send_his_status: json['send_his_status'] as bool?,
      sup_item_borrow_id: json['sup_item_borrow_id'] as String?,
      sup_item_trans_ref_id: json['sup_item_trans_ref_id'] as String?,
      sup_withdraw_line_id: json['sup_withdraw_line_id'] as String?,
      remark: json['remark'] as String?,
    );

Map<String, dynamic> _$ItemWithdrawToJson(ItemWithdraw instance) =>
    <String, dynamic>{
      'sup_item_id': instance.sup_item_id,
      'stock_department': instance.stock_department,
      'dept_current_balance': instance.dept_current_balance,
      'stock_current_balance': instance.stock_current_balance,
      'sup_item': instance.sup_item,
      'id': instance.id,
      'doc_type': instance.doc_type,
      'type': instance.type,
      'sup_control_register_id': instance.sup_control_register_id,
      'sup_acceptance_id': instance.sup_acceptance_id,
      'sup_withdraw_id': instance.sup_withdraw_id,
      'sup_transfer_id': instance.sup_transfer_id,
      'sup_return_id': instance.sup_return_id,
      'sup_borrow_id': instance.sup_borrow_id,
      'date': instance.date,
      'stock': instance.stock,
      'qty': instance.qty,
      'balance': instance.balance,
      'price_per_unit': instance.price_per_unit,
      'price': instance.price,
      'price_pay': instance.price_pay,
      'discount': instance.discount,
      'total': instance.total,
      'hr_ci_department_id': instance.hr_ci_department_id,
      'hr_ci_department_2_id': instance.hr_ci_department_2_id,
      'status': instance.status,
      'sup_vendor_id': instance.sup_vendor_id,
      'exp_date': instance.exp_date,
      'sup_item_return_id': instance.sup_item_return_id,
      'lot_maker': instance.lot_maker,
      'asset_status': instance.asset_status,
      'price_stock': instance.price_stock,
      'price_qty': instance.price_qty,
      'price_balance': instance.price_balance,
      'sup_sub_withdraw_id': instance.sup_sub_withdraw_id,
      'qty_req_withdraw': instance.qty_req_withdraw,
      'sup_deposit_id': instance.sup_deposit_id,
      'brand': instance.brand,
      'model': instance.model,
      'sup_acceptance_free_id': instance.sup_acceptance_free_id,
      'sup_unit_id': instance.sup_unit_id,
      'volume': instance.volume,
      'pack': instance.pack,
      'register_asset_status': instance.register_asset_status,
      'send_his_status': instance.send_his_status,
      'sup_item_borrow_id': instance.sup_item_borrow_id,
      'sup_item_trans_ref_id': instance.sup_item_trans_ref_id,
      'sup_withdraw_line_id': instance.sup_withdraw_line_id,
      'remark': instance.remark,
    };
